Script to run action locally
railsware/github-actions pull request #6
Opened 2020-11-03 12:52 UTC by IgorDobryn

2020-11-03 18:08 UTC, jweslley approved these changes

2020-11-05 15:37 UTC, fuksito approved these changes

2020-11-06 20:32 UTC, le0pard requested changes
https://www.npmjs.com/package/fs - why?

2020-11-06 20:32 UTC, le0pard commented on package.json
> +    "fs": "^0.0.1-security",
WAT? node.js have build in `fs` module.

2020-11-09 09:11 UTC, IgorDobryn commented on package.json
> +    "fs": "^0.0.1-security",
Good catch!

2020-11-09 11:05 UTC, IgorDobryn commented on package.json
> +    "fs": "^0.0.1-security",
@le0pard updated.

2020-11-09 11:06 UTC, le0pard approved these changes

2020-11-09 11:26 UTC, merged